# fly.toml app configuration file generated for misanc21-to-do-app on 2023-07-04T16:12:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misanc21-to-do-app"
primary_region = "gdl"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
